forge "https://forge.puppetlabs.com"

mod "puppetlabs/stdlib",     "4.11.0"
mod "puppetlabs/concat",     "1.2.5"
mod "puppetlabs/apache",     "1.9.0"
mod "puppetlabs/mysql",      "2.3.1"
mod "puppetlabs/firewall",   "1.8.1"
mod "puppetlabs/postgresql", "4.7.1"
